version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    env_file:
      - .env.development
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: